spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jspring
    username: sa
    password:
    driver-class-name: org.h2.Driver

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        # show_sql: true
        format_sql: true
  logging.level:
    org.hibernate.SQL: debug
  # org.hibernate.type: trace

jwt:
  secret:
    key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=
  expiration: 3600000