#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/jspring
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  thymeleaf:
#    cache: false
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#        # show_sql: true
#        format_sql: true
#  logging.level:
#    org.hibernate.SQL: debug
#  # org.hibernate.type: trace
#
#jwt:
#  secret:
#    key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=
#  expiration: 3600000
spring:
  datasource:
    url: jdbc:postgresql://13.124.28.30:5432/test
    username: jtw
    password: 1234
    driver-class-name: org.postgresql.Driver

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  logging.level:
    org.hibernate.SQL: debug

jwt:
  secret:
    key: 7ZWt7ZW0OTntmZTsnbTtjIXtlZzqta3snYTrhIjrqLjshLjqs4TroZzrgpjslYTqsIDsnpDtm4zrpa3tlZzqsJzrsJzsnpDrpbzrp4zrk6TslrTqsIDsnpA=
  expiration: 3600000